- name: use AWS Role
  hosts: localhost
  become: yes
  tags:
    - aws
  roles:
    - aws

- name: use Docker Role
  hosts: launched_instances
  become: yes
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: "{{ playbook_dir }}/cloud.pem"
  tags:
    - docker
  roles:
    - docker

- name: use Database Role
  hosts: launched_instances
  become: yes
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: "{{ playbook_dir }}/cloud.pem"
  tags:
    - database
  roles:
    - database

- name: use Wordpress Role
  hosts: launched_instances
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: "{{ playbook_dir }}/cloud.pem"
  become: yes
  tags:
    - wordpress
  roles:
    - wordpress

- name: use Webserver Role
  hosts: launched_instances
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: "{{ playbook_dir }}/cloud.pem"
  become: yes
  tags:
    - webserver
  roles:
    - webserver
