---
- name: Setup Ubuntu System and Install Docker
  hosts: local
  vars:
    ansible_user: "moumni"
  become: yes
  tasks:
    - name: Update APT package lists
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - curl
          - gnupg
          - software-properties-common
          - ca-certificates
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Prepare system for Docker installation
      block:
        - name: Install required packages for Docker repository
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
            state: present
            update_cache: yes

        - name: Create keyrings directory
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Download Docker GPG key
          ansible.builtin.shell:
            cmd: curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
            creates: /etc/apt/keyrings/docker.asc

        - name: Set appropriate permissions for Docker GPG key
          file:
            path: /etc/apt/keyrings/docker.asc
            mode: '0644'

        - name: Add Docker repository
          ansible.builtin.shell:
            cmd: >
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc]
              https://download.docker.com/linux/debian
              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            creates: /etc/apt/sources.list.d/docker.list

        - name: Update apt cache
          apt:
            update_cache: yes

        - name: Install Docker packages
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: latest
            update_cache: yes

        - name: Ensure Docker service is running
          service:
            name: docker
            state: started
            enabled: yes

        - name: Add current user to docker group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes

- name: use Database Role
  hosts: localhost
  roles:
    - database
