- name: use Docker Role
  hosts: localhost
  become: yes
  tags:
    - docker
  roles:
    - docker

- name: use Database Role
  hosts: localhost
  become: yes
  tags:
    - database
  roles:
    - database

- name: use Wordpress Role
  hosts: localhost
  become: yes
  tags:
    - wordpress
  roles:
    - wordpress

- name: use Webserver Role
  hosts: localhost
  tags:
    - webserver
  roles:
    - webserver
